import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Alert, ActivityIndicator } from 'react-native';
import Icon from '@expo/vector-icons/MaterialIcons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useData } from '../context/DataContext';
import { COLORS, SIZES, SHADOWS } from '../utils/theme';
import Header from '../components/Header';

export default function ExportDataScreen() {
  const { transactions, customers, getCurrencySymbol, settings } = useData();
  const [format, setFormat] = useState('pdf');
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);
    try {
      const currencySymbol = getCurrencySymbol();
      let tableRows = '';

      transactions.forEach((t, index) => {
        const customerName = customers.find(c => (c.id === t.customerId || c._id === t.customerId))?.name || 'Unknown';
        const dateStr = new Date(t.date).toLocaleDateString();
        const typeLabel = t.type === 'gave' ? 'GAVE (Credit)' : 'GOT (Received)';
        const amountColor = t.type === 'gave' ? '#dc3545' : '#198754';
        
        tableRows += `
          <tr style="background-color: ${index % 2 === 0 ? '#f8fafc' : '#ffffff'};">
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; color: #475569;">${dateStr}</td>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #1e293b;">${customerName}</td>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; color: ${amountColor}; font-weight: bold;">${typeLabel}</td>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; text-align: right; font-weight: bold; color: #0f172a;">${currencySymbol}${t.amount.toLocaleString()}</td>
            <td style="padding: 12px 15px; border-bottom: 1px solid #e2e8f0; color: #64748b;">${t.note || '-'}</td>
          </tr>
        `;
      });

      const logoSvg = `data:image/svg+xml;utf8,<svg width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="%230f766e" /><path d="M12 28V12L20 20L28 12V28" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

      const htmlContent = `
        <html>
        <head>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; padding: 40px; margin: 0; background: #fff; }
            .header-table { width: 100%; margin-bottom: 40px; border-bottom: 3px solid #0f766e; padding-bottom: 20px; }
            .logo-cell { width: 60px; vertical-align: top; }
            .business-name { font-size: 28px; font-weight: 800; color: #0f766e; margin-bottom: 4px; }
            .app-name { font-size: 14px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
            .business-details { font-size: 13px; color: #475569; text-align: right; line-height: 1.6; }
            .title { font-size: 22px; font-weight: bold; color: #1e293b; margin-bottom: 20px; letter-spacing: 0.5px; }
            .ledger-table { width: 100%; border-collapse: collapse; margin-top: 10px; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .ledger-table th { background-color: #0f766e; color: white; padding: 15px; text-align: left; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
            .footer { margin-top: 60px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
          </style>
        </head>
        <body>
          <table class="header-table">
            <tr>
              <td class="logo-cell">
                <img src="${logoSvg}" alt="Balance Book Logo" width="48" height="48" style="border-radius: 10px; box-shadow: 0 4px 6px rgba(15, 118, 110, 0.2);" />
              </td>
              <td style="vertical-align: top; padding-left: 15px;">
                <div class="business-name">${settings.businessName || 'Balance Book Merchant'}</div>
                <div class="app-name">Generated by Balance Book</div>
              </td>
              <td class="business-details">
                <div><strong>Phone:</strong> ${settings.businessPhone || 'N/A'}</div>
                <div><strong>Address:</strong> ${settings.businessAddress || 'N/A'}</div>
                <div><strong>Date Generated:</strong> ${new Date().toLocaleDateString()}</div>
              </td>
            </tr>
          </table>

          <div class="title">Complete Ledger Statement</div>

          <table class="ledger-table">
            <thead>
              <tr>
                <th style="width: 15%;">Date</th>
                <th style="width: 25%;">Customer</th>
                <th style="width: 20%;">Transaction Type</th>
                <th style="width: 15%; text-align: right;">Amount</th>
                <th style="width: 25%;">Details / Note</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows || '<tr><td colspan="5" style="text-align:center; padding:30px; color:#94a3b8; font-size: 15px;">No transaction entries found.</td></tr>'}
            </tbody>
          </table>

          <div class="footer">
            <strong>BALANCE BOOK APP</strong> — Secured and Verified Ledger Log
          </div>
        </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri);
    } catch (error) {
      Alert.alert('Error', 'Failed to generate statement export.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={{ flex: 1, backgroundColor: COLORS.surface }}>
      <Header />
      <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
        <View style={styles.card}>
          <Text style={styles.title}>Generate a highly-detailed, beautifully managed PDF Statement containing your entire ledger history.</Text>

          {loading ? (
            <ActivityIndicator color={COLORS.primary} style={{ marginTop: 24, marginBottom: 24 }} size="large" />
          ) : (
            <TouchableOpacity style={styles.exportBtn} onPress={handleExport}>
              <Icon name="picture-as-pdf" size={24} color="#fff" />
              <Text style={styles.exportBtnText}>Generate PDF Report</Text>
            </TouchableOpacity>
          )}

          <Text style={styles.recentTitle}>RECENT EXPORTS</Text>
          <View style={styles.recentItem}><Text style={styles.recentText}>Ledger_Statement_Summary.pdf - Just Now • 4.5 MB</Text></View>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  card: { backgroundColor: '#fff', margin: 16, padding: 24, borderRadius: 16, ...SHADOWS.md },
  title: { fontSize: 14, color: COLORS.text, marginBottom: 30, fontWeight: '500', lineHeight: 22, textAlign: 'center' },
  exportBtn: { backgroundColor: '#0f766e', padding: 16, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10, ...SHADOWS.md, marginBottom: 20 },
  exportBtnText: { color: '#fff', fontWeight: '800', fontSize: 16 },
  recentTitle: { marginTop: 28, fontWeight: '700', fontSize: 11, color: COLORS.textLight, letterSpacing: 0.5, marginBottom: 8 },
  recentItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eee' },
  recentText: { fontSize: 12, color: COLORS.text, fontWeight: '500' },
});
