export const CURRENCIES = [
  { code: 'USD', symbol: '$', label: 'United States Dollar ($)' },
  { code: 'EUR', symbol: '€', label: 'Euro (€)' },
  { code: 'GBP', symbol: '£', label: 'British Pound (£)' },
  { code: 'INR', symbol: '₹', label: 'Indian Rupee (₹)' },
  { code: 'PKR', symbol: 'Rs.', label: 'Pakistani Rupee (Rs.)' },
  { code: 'AED', symbol: 'د.إ', label: 'UAE Dirham (د.إ)' },
  { code: 'SAR', symbol: '﷼', label: 'Saudi Riyal (﷼)' },
  { code: 'CAD', symbol: 'C$', label: 'Canadian Dollar (C$)' },
  { code: 'AUD', symbol: 'A$', label: 'Australian Dollar (A$)' },
  { code: 'JPY', symbol: '¥', label: 'Japanese Yen (¥)' },
  { code: 'CNY', symbol: '¥', label: 'Chinese Yuan (¥)' },
  { code: 'SGD', symbol: 'S$', label: 'Singapore Dollar (S$)' },
  { code: 'NZD', symbol: 'NZ$', label: 'New Zealand Dollar (NZ$)' },
  { code: 'CHF', symbol: 'CHF', label: 'Swiss Franc (CHF)' },
  { code: 'HKD', symbol: 'HK$', label: 'Hong Kong Dollar (HK$)' },
  { code: 'RUB', symbol: '₽', label: 'Russian Ruble (₽)' },
  { code: 'BRL', symbol: 'R$', label: 'Brazilian Real (R$)' },
  { code: 'ZAR', symbol: 'R', label: 'South African Rand (R)' },
  { code: 'MXN', symbol: 'Mex$', label: 'Mexican Peso (Mex$)' },
  { code: 'TRY', symbol: '₺', label: 'Turkish Lira (₺)' },
  { code: 'SEK', symbol: 'kr', label: 'Swedish Krona (kr)' },
  { code: 'NOK', symbol: 'kr', label: 'Norwegian Krone (kr)' },
  { code: 'DKK', symbol: 'kr', label: 'Danish Krone (kr)' },
  { code: 'ILS', symbol: '₪', label: 'Israeli New Shekel (₪)' },
  { code: 'PHP', symbol: '₱', label: 'Philippine Peso (₱)' },
  { code: 'IDR', symbol: 'Rp', label: 'Indonesian Rupiah (Rp)' },
  { code: 'MYR', symbol: 'RM', label: 'Malaysian Ringgit (RM)' },
  { code: 'THB', symbol: '฿', label: 'Thai Baht (฿)' },
  { code: 'VND', symbol: '₫', label: 'Vietnamese Dong (₫)' },
  { code: 'KWD', symbol: 'K.D.', label: 'Kuwaiti Dinar (K.D.)' },
  { code: 'QAR', symbol: 'QR', label: 'Qatar Riyal (QR)' },
  { code: 'OMR', symbol: 'OR', label: 'Omani Rial (OR)' },
  { code: 'BHD', symbol: 'BD', label: 'Bahraini Dinar (BD)' },
  { code: 'EGP', symbol: 'LE', label: 'Egyptian Pound (LE)' },
  { code: 'KES', symbol: 'KSh', label: 'Kenyan Shilling (KSh)' },
  { code: 'NGN', symbol: '₦', label: 'Nigerian Naira (₦)' },
  { code: 'GHS', symbol: 'GH₵', label: 'Ghanaian Cedi (GH₵)' },
  { code: 'BDT', symbol: '৳', label: 'Bangladeshi Taka (৳)' },
  { code: 'LKR', symbol: 'Rs.', label: 'Sri Lankan Rupee (Rs.)' },
  { code: 'NPR', symbol: 'Rs.', label: 'Nepalese Rupee (Rs.)' },
  { code: 'PLN', symbol: 'zł', label: 'Polish Zloty (zł)' },
  { code: 'COP', symbol: 'COL$', label: 'Colombian Peso (COL$)' },
  { code: 'CLP', symbol: 'CLP$', label: 'Chilean Peso (CLP$)' },
  { code: 'PEN', symbol: 'S/.', label: 'Peruvian Sol (S/.)' },
  { code: 'ARS', symbol: '$', label: 'Argentine Peso ($)' },
];
